version: '3.8'

services:
  meuDB:
    image: mysql:5.7
    container_name: ContainerBD
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: urubu100
      MYSQL_DATABASE: banco1
      MYSQL_USER: diego
      MYSQL_PASSWORD: urubu100
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3307:3306"
    networks:
      app_net:
        ipv4_address: 172.20.0.2

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
