/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Individual;

import Jdbc.ConexaoBanco;
import Jdbc.ConexaoBancoLocal;
import Jdbc.Usuario;
import Jdbc.UsuarioRowMapper;
import JdbcCommands.InsertLogdeUso;
import JdbcCommands.InsertRegistro;
import JdbcCommands.SelectUser;
import Looca.ShowSistema;
import java.io.File;
import java.util.List;
import java.util.Scanner;
import org.springframework.jdbc.core.JdbcTemplate;

/**
 *
 * @author diego
 */
public class EasyWare extends javax.swing.JFrame {

    /**
     * Creates new form EasyWare
     */
    public EasyWare() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_email = new javax.swing.JLabel();
        input_email = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        label_senha = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        input_password = new javax.swing.JTextField();
        label_mensagem = new javax.swing.JLabel();
        label_logo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        label_email2 = new javax.swing.JLabel();
        label_logo2 = new javax.swing.JLabel();
        label_email3 = new javax.swing.JLabel();
        label_email4 = new javax.swing.JLabel();
        btnInnovation = new javax.swing.JButton();
        label_email5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(25, 25, 25));
        jPanel1.setForeground(new java.awt.Color(25, 25, 25));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 500));

        label_email.setFont(new java.awt.Font("FreeSans", 1, 14)); // NOI18N
        label_email.setForeground(new java.awt.Color(255, 255, 255));
        label_email.setText("Email:");

        input_email.setBackground(new java.awt.Color(25, 25, 25));
        input_email.setForeground(new java.awt.Color(255, 255, 255));
        input_email.setBorder(null);
        input_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_emailActionPerformed(evt);
            }
        });

        btnLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnLogin.setFont(new java.awt.Font("FreeSans", 1, 15)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(0, 0, 0));
        btnLogin.setText("Login");
        btnLogin.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        label_senha.setFont(new java.awt.Font("FreeSans", 1, 14)); // NOI18N
        label_senha.setForeground(new java.awt.Color(255, 255, 255));
        label_senha.setText("Senha:");

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        input_password.setBackground(new java.awt.Color(25, 25, 25));
        input_password.setForeground(new java.awt.Color(255, 255, 255));
        input_password.setBorder(null);
        input_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_passwordActionPerformed(evt);
            }
        });

        label_mensagem.setBackground(new java.awt.Color(255, 255, 255));
        label_mensagem.setForeground(new java.awt.Color(255, 255, 255));
        label_mensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        label_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Individual/logo-light (2).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(label_logo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(label_email)
                                .addGap(188, 188, 188))
                            .addComponent(input_email)
                            .addComponent(label_senha)
                            .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator2)
                            .addComponent(label_mensagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(input_password, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(label_logo)
                .addGap(48, 48, 48)
                .addComponent(label_email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label_senha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_mensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(25, 25, 25));
        jPanel2.setForeground(new java.awt.Color(25, 25, 25));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 500));

        label_email2.setFont(new java.awt.Font("FreeSans", 3, 24)); // NOI18N
        label_email2.setForeground(new java.awt.Color(255, 255, 255));
        label_email2.setText("Login realizado!");

        label_logo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Individual/logo-light (2).png"))); // NOI18N

        label_email3.setFont(new java.awt.Font("FreeSans", 2, 14)); // NOI18N
        label_email3.setForeground(new java.awt.Color(255, 255, 255));
        label_email3.setText("caso o computador esteja lento, aperte o botao");

        label_email4.setFont(new java.awt.Font("FreeSans", 2, 14)); // NOI18N
        label_email4.setForeground(new java.awt.Color(255, 255, 255));
        label_email4.setText("seus dados estão sendo registrados,");

        btnInnovation.setBackground(new java.awt.Color(255, 255, 255));
        btnInnovation.setFont(new java.awt.Font("FreeSans", 1, 15)); // NOI18N
        btnInnovation.setForeground(new java.awt.Color(0, 0, 0));
        btnInnovation.setText("Limpar Máquina");
        btnInnovation.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnInnovation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInnovation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInnovationActionPerformed(evt);
            }
        });

        label_email5.setFont(new java.awt.Font("FreeSans", 2, 14)); // NOI18N
        label_email5.setForeground(new java.awt.Color(255, 255, 255));
        label_email5.setText("minimize a tela e tenha um bom serviço!");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 40, Short.MAX_VALUE)
                .addComponent(label_email3, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(label_email2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(96, 96, 96)
                            .addComponent(label_logo2)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btnInnovation, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(label_email5, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(label_email4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(label_logo2)
                .addGap(18, 18, 18)
                .addComponent(label_email2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(label_email4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_email5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(label_email3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnInnovation, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void input_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_emailActionPerformed

    private void input_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_passwordActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        SelectUser select = new SelectUser();
        InsertLogdeUso loguso = new InsertLogdeUso();
        InsertRegistro inreg = new InsertRegistro();
        ShowSistema sis = new ShowSistema();
        
        ConexaoBanco conexaoBanco = new ConexaoBanco();
        JdbcTemplate conexao = conexaoBanco.getConnection();
        
        String email = String.valueOf(input_email.getText());
        String senha = String.valueOf(input_password.getText());

        List<Usuario> listaObjetoUsuario = conexao.query(
                "select * from usuario where email = ? and senha = ?", 
                new UsuarioRowMapper(), email, senha);
        
        if (email.isEmpty() || senha.isEmpty()) {
            System.out.println("Usuário ou Senha vazio(a)!");
            label_mensagem.setText("Usuário ou Senha vazio(a)");
        } else {
            select.selectAndInsert(email, senha);
            
            if (select.isLoginValido()) {
                System.out.println("Login deu certo!");
                
                jPanel1.setVisible(false);
                jPanel2.setVisible(true);
                
                loguso.validacao(email, senha);
                inreg.insert(email, senha);
                
            } else {
                System.out.println("Login deu errado");
                label_mensagem.setText("Usuário ou Senha inválidos!");

            }
        }

    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnInnovationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInnovationActionPerformed
        // TODO add your handling code here:
        
        String diretorio = "/home/root/Downloads/Teste_arquivos"; // Substitua pelo diretório desejado
        CleanerLocal cleaner = new CleanerLocal();
        
        File[] arquivos = new File(diretorio).listFiles();
        if (arquivos != null) {
            for (File arquivo : arquivos) {
                if (cleaner.isInativo(arquivo.toPath())) {
                    if (cleaner.fazerBackup(arquivo)) {
                        if (arquivo.delete()) {
                            System.out.println("Arquivo " + arquivo.getName() + " excluído.");
                        } else {
                            System.out.println("Erro ao excluir arquivo " + arquivo.getName());
                        }
                    } else {
                        System.out.println("Erro ao fazer backup do arquivo " + arquivo.getName());
                    }
                } else {
                    System.out.println(arquivo.getName() + " é recente.");
                }
            }
        }
    }//GEN-LAST:event_btnInnovationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EasyWare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EasyWare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EasyWare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EasyWare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EasyWare().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInnovation;
    private javax.swing.JButton btnLogin;
    private javax.swing.JTextField input_email;
    private javax.swing.JTextField input_password;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel label_email;
    private javax.swing.JLabel label_email2;
    private javax.swing.JLabel label_email3;
    private javax.swing.JLabel label_email4;
    private javax.swing.JLabel label_email5;
    private javax.swing.JLabel label_logo;
    private javax.swing.JLabel label_logo2;
    private javax.swing.JLabel label_mensagem;
    private javax.swing.JLabel label_senha;
    // End of variables declaration//GEN-END:variables
}
